'use strict';
const datasets={business:{title:'Бизнес · план-факт',chart:'Выручка, млн сом',unit:'млн сом',q1:{fact:[2.1,2.4,2.5],plan:[2.3,2.4,2.6]},q2:{fact:[2.6,2.8,3],plan:[2.5,2.7,2.8]}},finance:{title:'Финансы · движение денег',chart:'Поступления и выплаты, млн сом',unit:'млн сом',q1:{fact:[2.1,2.4,2.3],plan:[2,2.5,2.1]},q2:{fact:[2.6,2.8,2.4],plan:[2.3,2.5,2.7]}},project:{title:'Проект · накопленный прогресс',chart:'Выполнение работ, %',unit:'%',q1:{fact:[12,22,31],plan:[15,25,35]},q2:{fact:[44,56,68],plan:[50,62,75]}}};
let view='business';const byId=id=>document.getElementById(id);const fmt=(n,d=1)=>n.toLocaleString('ru-RU',{maximumFractionDigits:d});const sum=a=>a.reduce((x,y)=>x+y,0);const signed=(n,d=1)=>(n>0?'+':n<0?'−':'')+fmt(Math.abs(n),d);
function render(){const p=byId('period').value;const data=datasets[view],v=data[p];const months=p==='q1'?['Январь','Февраль','Март']:['Апрель','Май','Июнь'];let m,question,explain,formula;
if(view==='business'){const f=sum(v.fact),plan=sum(v.plan),delta=(f/plan-1)*100;m=[['Выручка / факт',fmt(f)+' млн','План: '+fmt(plan)+' млн сом'],['Отклонение',signed(delta)+'%',signed(f-plan)+' млн сом'],['Среднее за месяц',fmt(f/3,2)+' млн','За выбранный квартал']];question=delta>=0?'Выручка выше плана. А прибыль?':'Выручка ниже плана. Где причина?';explain='План-факт показывает отклонение. Чтобы оценить прибыль, нужны расходы и себестоимость — этих данных в демонстрации нет.';formula='Выручка = сумма факта за квартал. Отклонение = (факт / план − 1) × 100%. Среднее = факт / 3.';}
else if(view==='finance'){const incoming=sum(v.fact),outgoing=sum(v.plan),flow=incoming-outgoing,opening=p==='q1'?1.8:2;m=[['Поступления',fmt(incoming)+' млн','За выбранный квартал'],['Чистый денежный поток',signed(flow)+' млн','Поступления минус выплаты'],['Остаток на конец',fmt(opening+flow)+' млн','На начало: '+fmt(opening)+' млн сом']];question='Хватит денег на следующие платежи?';explain='Итоговый остаток не раскрывает сроки будущих обязательств. Для оценки ликвидности нужен платёжный календарь.';formula='Чистый поток = поступления − выплаты. Остаток на конец = остаток на начало + чистый поток. Все суммы в млн сом.';}
else{const fact=v.fact[2],plan=v.plan[2];m=[['Прогресс / факт',fmt(fact)+'%','План: '+fmt(plan)+'%'],['Отставание',signed(fact-plan)+' п. п.','Разница факта и плана'],['Осталось выполнить',fmt(100-fact)+'%','До 100% согласованного объёма']];question='Какие работы сдерживают прогресс?';explain='Отставание в процентах не равно задержке в днях. Проверяем критический путь, оставшиеся длительности и ресурсы в графике.';formula='Прогресс — накопленный процент выполнения на конец месяца. Отклонение = факт − план в процентных пунктах. Остаток = 100% − факт.';}
byId('dash-heading').textContent=data.title;byId('metrics').innerHTML=m.map(([label,value,note])=>`<div class="metric"><small>${label}</small><strong>${value}</strong><span>${note}</span></div>`).join('');byId('chart-label').textContent=data.chart;byId('insight-title').textContent=question;byId('insight-text').textContent=explain;byId('formula').textContent=formula;byId('month-labels').innerHTML=months.map(x=>`<span>${x}</span>`).join('');byId('fact-header').textContent=view==='finance'?'Поступления':'Факт';byId('plan-header').textContent=view==='finance'?'Выплаты':'План';byId('data-caption').textContent=data.chart+' · условные данные';byId('data-table').innerHTML=months.map((x,i)=>`<tr><th scope="row">${x}</th><td>${fmt(v.fact[i])}</td><td>${fmt(v.plan[i])}</td></tr>`).join('');
const max=view==='project'?100:Math.ceil(Math.max(...v.fact,...v.plan)*1.2*10)/10;const y=n=>200-(n/max)*170;const xs=[115,320,525];let svg=`<title id="chart-title">${data.chart} — ${months.join(', ')}</title><desc id="chart-desc">Условные данные. ${months.map((x,i)=>`${x}: ${view==='finance'?'поступления':'факт'} ${fmt(v.fact[i])}, ${view==='finance'?'выплаты':'план'} ${fmt(v.plan[i])} ${data.unit}`).join('; ')}.</desc>`;
for(let i=0;i<=4;i++){const n=max*i/4;svg+=`<line x1="45" x2="630" y1="${y(n)}" y2="${y(n)}" stroke="#405b4e"/><text x="0" y="${y(n)+4}" fill="#bdcebf" font-size="12">${fmt(n)}</text>`;}
v.fact.forEach((n,i)=>{svg+=`<rect x="${xs[i]-35}" y="${y(n)}" width="34" height="${200-y(n)}" rx="2" fill="#deef9b"/><rect x="${xs[i]+5}" y="${y(v.plan[i])}" width="34" height="${200-y(v.plan[i])}" rx="2" fill="#789b92"/>`;});byId('chart').innerHTML=svg;document.querySelector('.legend').innerHTML=view==='finance'?'<span>● Поступления</span><span>○ Выплаты</span>':'<span>● Факт</span><span>○ План</span>';
}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();}));byId('period').addEventListener('change',render);render();