'use strict';
(()=>{
const el=id=>document.getElementById(id);const money=n=>n.toLocaleString('ru-RU')+' сом';
const packages={audit:{title:'Диагностика и аналитика бизнеса',base:150000,included:5,text:'Разберём источники, согласуем показатели, проверим качество данных и соберём единую модель.'},bi:{title:'Дашборды и автоматизация',base:300000,included:6,text:'Свяжем до 6 согласованных источников, настроим модель Power BI и до 5 страниц отчётности.'},finance:{title:'Финансовый контроль',base:450000,included:5,text:'Соберём ДДС, бюджет и платёжный календарь одной компании, чтобы разбирать отклонения и сценарии.'},build:{title:'Аналитика строительного проекта',base:650000,included:5,text:'Соединим объёмы, затраты, закрытие и график одного объекта в согласованный управленческий отчёт.'}};
let currentBrief='';
function quote(){const key=el('quote-type').value,p=packages[key],sources=Number(el('quote-sources').value),reports=Number(el('quote-reports').value),clean=el('quote-clean').checked,training=el('quote-training').checked,support=el('quote-support').checked;const extraSources=Math.max(0,sources-p.included);const price=p.base+extraSources*25000+reports*35000+(clean?60000:0)+(training?40000:0);
el('sources-output').textContent=sources;el('reports-output').textContent=reports;el('quote-price').textContent='от '+money(price);el('quote-title').textContent=p.title;el('quote-monthly').textContent=support?'Сопровождение отдельно: от 180 000 сом / месяц':'Разовый проект · сопровождение не выбрано';el('quote-summary').textContent=`${sources} источников; дополнительных отчётов: ${reports}. ${extraSources?'Источников сверх пакета: '+extraSources+'. ':''}${clean?'Расширенная очистка данных. ':''}${training?'Дополнительное обучение команды. ':''}`;
currentBrief=`Здравствуйте, Khushbakht! Хочу обсудить проект «${p.title}».\nИсточников: ${sources}. Дополнительных отчётов: ${reports}.\nРасширенная очистка: ${clean?'да':'нет'}. Обучение: ${training?'да':'нет'}.\nПредварительный бюджет: от ${money(price)} за проект. ${support?'Сопровождение: от 180 000 сом / месяц.':'Без месячного сопровождения.'}\nПонимаю, что точная цена зависит от проверки данных. Моя задача: `;el('quote-whatsapp').href='https://wa.me/996226003545?text='+encodeURIComponent(currentBrief);el('copy-status').textContent='';}
el('quote-form').addEventListener('input',quote);el('quote-form').addEventListener('change',quote);el('quote-form').addEventListener('reset',()=>setTimeout(quote,0));
document.querySelectorAll('[data-task]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.task,p=packages[key];document.querySelectorAll('[data-task]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));el('recommend-title').textContent=p.title;el('recommend-text').textContent=p.text;el('recommend-price').textContent='от '+money(p.base);el('quote-type').value=key;el('quote-sources').value=p.included;quote();}));
el('copy-brief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(currentBrief);el('copy-status').textContent='Бриф скопирован. Добавьте описание вашей задачи.';}catch{el('copy-status').textContent='Копирование недоступно. Откройте WhatsApp — бриф уже подготовлен.';}});
function cash(){const opening=Number(el('cash-open').value)/10,income=Number(el('cash-in').value)/10,out=Number(el('cash-out').value)/10,end=opening+income-out;const fmt=n=>n.toLocaleString('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1})+' млн сом';el('cash-open-output').textContent=fmt(opening);el('cash-in-output').textContent=fmt(income);el('cash-out-output').textContent=fmt(out);el('cash-end').textContent=fmt(end);el('cash-badge').textContent=end<0?'Дефицит на конец месяца':end===0?'Нулевой остаток':'Положительный остаток';document.querySelector('.scenario-result').dataset.negative=String(end<0);el('cash-explanation').textContent=end<0?'В этом условном сценарии выплаты превышают доступные деньги. Проверьте сроки поступлений и платежей, прежде чем обсуждать источник финансирования.':end===0?'Денег достаточно ровно на заданные выплаты, без остатка. Внутри месяца всё ещё может возникнуть разрыв.':'Положительный остаток по месяцу не исключает кассовый разрыв внутри месяца. Следующий шаг — проверить даты платежей.';}
['cash-open','cash-in','cash-out'].forEach(id=>el(id).addEventListener('input',cash));const presets={base:[20,30,25],delay:[20,10,35],cost:[20,30,60]};document.querySelectorAll('[data-cash]').forEach(b=>b.addEventListener('click',()=>{const v=presets[b.dataset.cash];['cash-open','cash-in','cash-out'].forEach((id,i)=>el(id).value=v[i]);cash();}));
document.querySelectorAll('#prepare-checks input').forEach(b=>b.addEventListener('change',()=>{const n=document.querySelectorAll('#prepare-checks input:checked').length;el('prepare-count').textContent=n+' / 5';el('prepare-progress').value=n;el('prepare-tip').textContent=n===5?'База для обсуждения готова. Можно перейти к выбору формата и бюджета.':n===0?'Начните с вопроса: какое решение должен помочь принять отчёт?':'Готово '+n+' из 5 пунктов. Необязательно ждать полного комплекта — начните с того, что уже есть.';}));quote();cash();
})();